name: Deploy site to production bucket

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: cfst-3457-e07e893812aafc0bc42e2aeec6f2-prodbucket-jecq8tq0ce01
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up node js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: | 
            npm ci
            npm run build 
      - name: Upload to S3
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }}/ --recursive --acl public-read
